//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.13 at 04:23:03 PM GMT+03:30 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.spring.ir/createapp002/object", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ir.spring.createapp002.object;
